language: java

dist: trusty

jdk:
  - oraclejdk8

sudo: false

script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash) -f my_cobertura.xml -t 498fc3a1-ff81-4dac-bbc9-b5748cb9caf1